version: "3.9"
services:
  pgdb:
    container_name: tenant_property_db_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: tenant_property_db
    ports:
      - "5432:5432"
    volumes:
      - ./tenant_property_db:/var/lib/postgresql/data/
    expose:
      - 5432
  adminer:
    container_name: db_client
    image: adminer
    restart: always
    ports:
      - 8080:8080