export const fakeProperties = [
  {
    id: 101,
    title: "Modern Studio Apartment in Queens",
    location: "Queens, NY",
    price: 2050,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["dishwasher", "pool access", "balcony"],
    type: "studio",
    availableFrom: "2025-09-02",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, pool access, and balcony. Available starting September 2, 2025 for $2050/month. Don't miss out!",
  },
  {
    id: 102,
    title: "Spacious 1 Bed Condo in San Francisco",
    location: "San Francisco, CA",
    price: 3150,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "gym access", "furnished", "hardwood floors"],
    type: "condo",
    availableFrom: "2025-07-28",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, gym access, furnished, and hardwood floors. Available starting July 28, 2025 for $3150/month. Don't miss out!",
  },
  {
    id: 103,
    title: "Charming 2 Bed Townhouse in Boston",
    location: "Boston, MA",
    price: 5000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["wifi", "pool access", "storage unit", "ev charging"],
    type: "townhouse",
    availableFrom: "2025-07-16",
    description:
      "Discover 2 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like wifi, pool access, storage unit, and ev charging. Available starting July 16, 2025 for $5000/month. Don't miss out!",
  },
  {
    id: 104,
    title: "Spacious 4 Bed House in Denver",
    location: "Denver, CO",
    price: 6350,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["in-unit laundry", "pet-friendly", "doorman", "balcony"],
    type: "house",
    availableFrom: "2025-11-20",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, pet-friendly, doorman, and balcony. Available starting November 20, 2025 for $6350/month. Don't miss out!",
  },
  {
    id: 105,
    title: "Modern 2 Bed Apartment in Chicago",
    location: "Chicago, IL",
    price: 3100,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["parking", "hardwood floors"],
    type: "apartment",
    availableFrom: "2025-10-09",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking and hardwood floors. Available starting October 9, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 106,
    title: "Spacious 3 Bed House in Manhattan",
    location: "Manhattan, NY",
    price: 7900,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "hardwood floors",
      "storage unit",
      "ev charging",
      "shared garden",
      "doorman",
      "pet-friendly",
    ],
    type: "house",
    availableFrom: "2025-07-06",
    description:
      "Discover 3 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, storage unit, ev charging, shared garden, doorman, and pet-friendly. Available starting July 6, 2025 for $7900/month. Don't miss out!",
  },
  {
    id: 107,
    title: "Charming 4 Bed House in Queens",
    location: "Queens, NY",
    price: 5150,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["doorman", "balcony", "shared garden"],
    type: "house",
    availableFrom: "2025-10-02",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like doorman, balcony, and shared garden. Available starting October 2, 2025 for $5150/month. Don't miss out!",
  },
  {
    id: 108,
    title: "Modern 2 Bed Condo in Atlanta",
    location: "Atlanta, GA",
    price: 2400,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["dishwasher", "furnished", "in-unit laundry"],
    type: "condo",
    availableFrom: "2026-01-29",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, furnished, and in-unit laundry. Available starting January 29, 2026 for $2400/month. Don't miss out!",
  },
  {
    id: 109,
    title: "Bright 5 Bed Apartment in Austin",
    location: "Austin, TX",
    price: 4900,
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["pet-friendly", "storage unit"],
    type: "apartment",
    availableFrom: "2025-07-05",
    description:
      "Discover 5 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly and storage unit. Available starting July 5, 2025 for $4900/month. Don't miss out!",
  },
  {
    id: 110,
    title: "Quaint 3 Bed Apartment in Queens",
    location: "Queens, NY",
    price: 2850,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["hardwood floors", "gym access", "wifi", "balcony"],
    type: "apartment",
    availableFrom: "2025-12-07",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, gym access, wifi, and balcony. Available starting December 7, 2025 for $2850/month. Don't miss out!",
  },
  {
    id: 111,
    title: "Cozy 2 Bed Apartment in Chicago",
    location: "Chicago, IL",
    price: 2600,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["central AC", "pet-friendly", "doorman"],
    type: "apartment",
    availableFrom: "2025-08-01",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, pet-friendly, and doorman. Available starting August 1, 2025 for $2600/month. Don't miss out!",
  },
  {
    id: 112,
    title: "Modern 3 Bed Apartment in Portland",
    location: "Portland, OR",
    price: 2750,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["furnished", "parking", "pool access", "in-unit laundry"],
    type: "apartment",
    availableFrom: "2025-12-01",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, parking, pool access, and in-unit laundry. Available starting December 1, 2025 for $2750/month. Don't miss out!",
  },
  {
    id: 113,
    title: "Luxurious 3 Bed Apartment in Austin",
    location: "Austin, TX",
    price: 3100,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["parking", "hardwood floors", "rooftop access", "pet-friendly"],
    type: "apartment",
    availableFrom: "2025-09-02",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking, hardwood floors, rooftop access, and pet-friendly. Available starting September 2, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 114,
    title: "Bright 4 Bed Condo in Seattle",
    location: "Seattle, WA",
    price: 6300,
    bedrooms: 4,
    bathrooms: 3,
    amenities: [
      "furnished",
      "pet-friendly",
      "central AC",
      "pool access",
      "wifi",
    ],
    type: "condo",
    availableFrom: "2025-08-16",
    description:
      "Discover 4 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, pet-friendly, central AC, pool access, and wifi. Available starting August 16, 2025 for $6300/month. Don't miss out!",
  },
  {
    id: 115,
    title: "Luxurious 2 Bed House in San Francisco",
    location: "San Francisco, CA",
    price: 6300,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "doorman",
      "in-unit laundry",
      "pool access",
      "balcony",
      "hardwood floors",
    ],
    type: "house",
    availableFrom: "2025-12-16",
    description:
      "Discover 2 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like doorman, in-unit laundry, pool access, balcony, and hardwood floors. Available starting December 16, 2025 for $6300/month. Don't miss out!",
  },
  {
    id: 116,
    title: "Spacious 1 Bed Condo in Manhattan",
    location: "Manhattan, NY",
    price: 4050,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["parking", "pet-friendly", "shared garden"],
    type: "condo",
    availableFrom: "2026-01-26",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking, pet-friendly, and shared garden. Available starting January 26, 2026 for $4050/month. Don't miss out!",
  },
  {
    id: 117,
    title: "Bright 1 Bed Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 1400,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "dishwasher",
      "gym access",
      "pet-friendly",
      "balcony",
      "central AC",
    ],
    type: "apartment",
    availableFrom: "2025-12-10",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, gym access, pet-friendly, balcony, and central AC. Available starting December 10, 2025 for $1400/month. Don't miss out!",
  },
  {
    id: 118,
    title: "Cozy 5 Bed Apartment in Los Angeles",
    location: "Los Angeles, CA",
    price: 5700,
    bedrooms: 5,
    bathrooms: 3,
    amenities: [
      "furnished",
      "parking",
      "pool access",
      "in-unit laundry",
      "gym access",
      "doorman",
    ],
    type: "apartment",
    availableFrom: "2025-09-17",
    description:
      "Discover 5 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, parking, pool access, in-unit laundry, gym access, and doorman. Available starting September 17, 2025 for $5700/month. Don't miss out!",
  },
  {
    id: 119,
    title: "Charming Studio Apartment in Boston",
    location: "Boston, MA",
    price: 2800,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["wifi", "balcony", "pet-friendly"],
    type: "studio",
    availableFrom: "2025-10-09",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like wifi, balcony, and pet-friendly. Available starting October 9, 2025 for $2800/month. Don't miss out!",
  },
  {
    id: 120,
    title: "Spacious 2 Bed Apartment in Nashville",
    location: "Nashville, TN",
    price: 1600,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["hardwood floors", "parking", "in-unit laundry"],
    type: "apartment",
    availableFrom: "2025-10-05",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, parking, and in-unit laundry. Available starting October 5, 2025 for $1600/month. Don't miss out!",
  },
  {
    id: 121,
    title: "Modern 1 Bed Condo in Seattle",
    location: "Seattle, WA",
    price: 4350,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["rooftop access", "wifi", "shared garden", "pool access"],
    type: "condo",
    availableFrom: "2025-10-05",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, wifi, shared garden, and pool access. Available starting October 5, 2025 for $4350/month. Don't miss out!",
  },
  {
    id: 122,
    title: "Cozy 5 Bed House in Austin",
    location: "Austin, TX",
    price: 5900,
    bedrooms: 5,
    bathrooms: 3,
    amenities: [
      "hardwood floors",
      "shared garden",
      "in-unit laundry",
      "gym access",
    ],
    type: "house",
    availableFrom: "2025-08-01",
    description:
      "Discover 5 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, shared garden, in-unit laundry, and gym access. Available starting August 1, 2025 for $5900/month. Don't miss out!",
  },
  {
    id: 123,
    title: "Bright 1 Bed Condo in Miami",
    location: "Miami, FL",
    price: 3100,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "pool access", "doorman", "balcony"],
    type: "condo",
    availableFrom: "2025-11-20",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, pool access, doorman, and balcony. Available starting November 20, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 124,
    title: "Modern 2 Bed Condo in Brooklyn",
    location: "Brooklyn, NY",
    price: 5400,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["in-unit laundry", "furnished", "doorman", "rooftop access"],
    type: "condo",
    availableFrom: "2025-09-08",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, furnished, doorman, and rooftop access. Available starting September 8, 2025 for $5400/month. Don't miss out!",
  },
  {
    id: 125,
    title: "Modern Studio Apartment in Manhattan",
    location: "Manhattan, NY",
    price: 3500,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["gym access", "wifi", "doorman", "balcony"],
    type: "studio",
    availableFrom: "2025-10-25",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, wifi, doorman, and balcony. Available starting October 25, 2025 for $3500/month. Don't miss out!",
  },
  {
    id: 126,
    title: "Charming Studio Apartment in Portland",
    location: "Portland, OR",
    price: 1850,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "wifi",
      "pet-friendly",
      "gym access",
      "storage unit",
    ],
    type: "studio",
    availableFrom: "2025-07-28",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, wifi, pet-friendly, gym access, and storage unit. Available starting July 28, 2025 for $1850/month. Don't miss out!",
  },
  {
    id: 127,
    title: "Quaint 1 Bed Condo in Boston",
    location: "Boston, MA",
    price: 3500,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "in-unit laundry",
      "wifi",
      "balcony",
      "doorman",
      "furnished",
    ],
    type: "condo",
    availableFrom: "2025-10-18",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, in-unit laundry, wifi, balcony, doorman, and furnished. Available starting October 18, 2025 for $3500/month. Don't miss out!",
  },
  {
    id: 128,
    title: "Modern 4 Bed House in Manhattan",
    location: "Manhattan, NY",
    price: 11300,
    bedrooms: 4,
    bathrooms: 3,
    amenities: [
      "parking",
      "balcony",
      "central AC",
      "dishwasher",
      "storage unit",
    ],
    type: "house",
    availableFrom: "2025-07-21",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking, balcony, central AC, dishwasher, and storage unit. Available starting July 21, 2025 for $11300/month. Don't miss out!",
  },
  {
    id: 129,
    title: "Luxurious 2 Bed Condo in Miami",
    location: "Miami, FL",
    price: 3100,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["doorman", "gym access", "storage unit", "balcony"],
    type: "condo",
    availableFrom: "2025-12-07",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like doorman, gym access, storage unit, and balcony. Available starting December 7, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 130,
    title: "Modern 2 Bed Apartment in Queens",
    location: "Queens, NY",
    price: 2750,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["furnished", "pool access", "balcony"],
    type: "apartment",
    availableFrom: "2025-10-09",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, pool access, and balcony. Available starting October 9, 2025 for $2750/month. Don't miss out!",
  },
  {
    id: 131,
    title: "Luxurious 2 Bed Townhouse in Brooklyn",
    location: "Brooklyn, NY",
    price: 6250,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "in-unit laundry",
      "balcony",
      "central AC",
      "shared garden",
      "parking",
    ],
    type: "townhouse",
    availableFrom: "2025-10-02",
    description:
      "Discover 2 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, balcony, central AC, shared garden, and parking. Available starting October 2, 2025 for $6250/month. Don't miss out!",
  },
  {
    id: 132,
    title: "Charming 2 Bed Townhouse in Seattle",
    location: "Seattle, WA",
    price: 5750,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "pool access",
      "storage unit",
      "dishwasher",
      "furnished",
      "balcony",
    ],
    type: "townhouse",
    availableFrom: "2025-10-18",
    description:
      "Discover 2 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pool access, storage unit, dishwasher, furnished, and balcony. Available starting October 18, 2025 for $5750/month. Don't miss out!",
  },
  {
    id: 133,
    title: "Quaint 4 Bed Apartment in Nashville",
    location: "Nashville, TN",
    price: 2850,
    bedrooms: 4,
    bathrooms: 2,
    amenities: ["pool access", "rooftop access"],
    type: "apartment",
    availableFrom: "2026-01-28",
    description:
      "Discover 4 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pool access and rooftop access. Available starting January 28, 2026 for $2850/month. Don't miss out!",
  },
  {
    id: 134,
    title: "Modern 3 Bed Condo in Manhattan",
    location: "Manhattan, NY",
    price: 8600,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["rooftop access", "gym access", "dishwasher", "pet-friendly"],
    type: "condo",
    availableFrom: "2025-07-26",
    description:
      "Discover 3 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, gym access, dishwasher, and pet-friendly. Available starting July 26, 2025 for $8600/month. Don't miss out!",
  },
  {
    id: 135,
    title: "Modern 3 Bed Townhouse in San Francisco",
    location: "San Francisco, CA",
    price: 8650,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "pet-friendly",
      "hardwood floors",
      "wifi",
      "pool access",
      "in-unit laundry",
    ],
    type: "townhouse",
    availableFrom: "2025-08-05",
    description:
      "Discover 3 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, hardwood floors, wifi, pool access, and in-unit laundry. Available starting August 5, 2025 for $8650/month. Don't miss out!",
  },
  {
    id: 136,
    title: "Modern 3 Bed House in Los Angeles",
    location: "Los Angeles, CA",
    price: 5000,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "furnished",
      "central AC",
      "rooftop access",
      "pool access",
      "dishwasher",
    ],
    type: "house",
    availableFrom: "2025-07-28",
    description:
      "Discover 3 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, central AC, rooftop access, pool access, and dishwasher. Available starting July 28, 2025 for $5000/month. Don't miss out!",
  },
  {
    id: 137,
    title: "Charming 3 Bed Apartment in Miami",
    location: "Miami, FL",
    price: 4150,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "furnished",
      "pet-friendly",
      "central AC",
      "doorman",
      "pool access",
    ],
    type: "apartment",
    availableFrom: "2025-09-17",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, pet-friendly, central AC, doorman, and pool access. Available starting September 17, 2025 for $4150/month. Don't miss out!",
  },
  {
    id: 138,
    title: "Modern Studio Apartment in Los Angeles",
    location: "Los Angeles, CA",
    price: 2750,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["central AC", "in-unit laundry", "doorman"],
    type: "studio",
    availableFrom: "2025-09-05",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, in-unit laundry, and doorman. Available starting September 5, 2025 for $2750/month. Don't miss out!",
  },
  {
    id: 139,
    title: "Spacious 3 Bed House in Brooklyn",
    location: "Brooklyn, NY",
    price: 7900,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "rooftop access",
      "balcony",
      "doorman",
      "hardwood floors",
      "central AC",
    ],
    type: "house",
    availableFrom: "2025-10-14",
    description:
      "Discover 3 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, balcony, doorman, hardwood floors, and central AC. Available starting October 14, 2025 for $7900/month. Don't miss out!",
  },
  {
    id: 140,
    title: "Modern Studio Apartment in Miami",
    location: "Miami, FL",
    price: 2150,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["doorman", "parking", "central AC", "wifi"],
    type: "studio",
    availableFrom: "2025-09-06",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like doorman, parking, central AC, and wifi. Available starting September 6, 2025 for $2150/month. Don't miss out!",
  },
  {
    id: 141,
    title: "Luxurious 1 Bed Apartment in Denver",
    location: "Denver, CO",
    price: 2300,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "in-unit laundry",
      "pet-friendly",
      "dishwasher",
      "shared garden",
    ],
    type: "apartment",
    availableFrom: "2025-08-09",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, pet-friendly, dishwasher, and shared garden. Available starting August 9, 2025 for $2300/month. Don't miss out!",
  },
  {
    id: 142,
    title: "Charming 2 Bed Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 1800,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["hardwood floors", "shared garden", "wifi", "storage unit"],
    type: "apartment",
    availableFrom: "2025-08-07",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, shared garden, wifi, and storage unit. Available starting August 7, 2025 for $1800/month. Don't miss out!",
  },
  {
    id: 143,
    title: "Quaint Studio Apartment in Brooklyn",
    location: "Brooklyn, NY",
    price: 3200,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      "rooftop access",
      "doorman",
      "central AC",
      "pet-friendly",
      "furnished",
    ],
    type: "studio",
    availableFrom: "2025-10-15",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, doorman, central AC, pet-friendly, and furnished. Available starting October 15, 2025 for $3200/month. Don't miss out!",
  },
  {
    id: 144,
    title: "Luxurious 1 Bed Condo in San Francisco",
    location: "San Francisco, CA",
    price: 5300,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "pet-friendly",
      "doorman",
      "balcony",
      "gym access",
      "hardwood floors",
    ],
    type: "condo",
    availableFrom: "2025-10-18",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, doorman, balcony, gym access, and hardwood floors. Available starting October 18, 2025 for $5300/month. Don't miss out!",
  },
  {
    id: 145,
    title: "Cozy 3 Bed Apartment in Nashville",
    location: "Nashville, TN",
    price: 2850,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "hardwood floors",
      "rooftop access",
      "pool access",
      "in-unit laundry",
      "ev charging",
    ],
    type: "apartment",
    availableFrom: "2025-09-29",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, rooftop access, pool access, in-unit laundry, and ev charging. Available starting September 29, 2025 for $2850/month. Don't miss out!",
  },
  {
    id: 146,
    title: "Charming 2 Bed Apartment in Manhattan",
    location: "Manhattan, NY",
    price: 6250,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "dishwasher",
      "doorman",
      "wifi",
      "central AC",
      "balcony",
      "storage unit",
    ],
    type: "apartment",
    availableFrom: "2025-07-27",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, doorman, wifi, central AC, balcony, and storage unit. Available starting July 27, 2025 for $6250/month. Don't miss out!",
  },
  {
    id: 147,
    title: "Luxurious 2 Bed Apartment in Portland",
    location: "Portland, OR",
    price: 1950,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["pet-friendly", "parking", "wifi"],
    type: "apartment",
    availableFrom: "2025-11-29",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, parking, and wifi. Available starting November 29, 2025 for $1950/month. Don't miss out!",
  },
  {
    id: 148,
    title: "Cozy 2 Bed Condo in Los Angeles",
    location: "Los Angeles, CA",
    price: 4200,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      "in-unit laundry",
      "furnished",
      "parking",
      "pool access",
      "hardwood floors",
    ],
    type: "condo",
    availableFrom: "2025-10-12",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, furnished, parking, pool access, and hardwood floors. Available starting October 12, 2025 for $4200/month. Don't miss out!",
  },
  {
    id: 149,
    title: "Modern 1 Bed Apartment in Atlanta",
    location: "Atlanta, GA",
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["in-unit laundry", "wifi", "storage unit"],
    type: "apartment",
    availableFrom: "2025-08-06",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, wifi, and storage unit. Available starting August 6, 2025 for $1800/month. Don't miss out!",
  },
  {
    id: 150,
    title: "Quaint Studio Apartment in Miami",
    location: "Miami, FL",
    price: 2300,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "pool access",
      "central AC",
      "wifi",
      "balcony",
    ],
    type: "studio",
    availableFrom: "2026-01-23",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, pool access, central AC, wifi, and balcony. Available starting January 23, 2026 for $2300/month. Don't miss out!",
  },
  {
    id: 151,
    title: "Spacious 4 Bed House in Seattle",
    location: "Seattle, WA",
    price: 9300,
    bedrooms: 4,
    bathrooms: 3,
    amenities: [
      "pool access",
      "in-unit laundry",
      "central AC",
      "dishwasher",
      "furnished",
      "shared garden",
    ],
    type: "house",
    availableFrom: "2025-11-20",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pool access, in-unit laundry, central AC, dishwasher, furnished, and shared garden. Available starting November 20, 2025 for $9300/month. Don't miss out!",
  },
  {
    id: 152,
    title: "Charming 2 Bed Apartment in Austin",
    location: "Austin, TX",
    price: 3100,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      "balcony",
      "doorman",
      "parking",
      "gym access",
      "wifi",
      "storage unit",
    ],
    type: "apartment",
    availableFrom: "2025-07-28",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like balcony, doorman, parking, gym access, wifi, and storage unit. Available starting July 28, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 153,
    title: "Spacious 2 Bed Apartment in Denver",
    location: "Denver, CO",
    price: 2700,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["hardwood floors", "furnished", "storage unit", "balcony"],
    type: "apartment",
    availableFrom: "2025-08-14",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, furnished, storage unit, and balcony. Available starting August 14, 2025 for $2700/month. Don't miss out!",
  },
  {
    id: 154,
    title: "Spacious 3 Bed Condo in Chicago",
    location: "Chicago, IL",
    price: 4250,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "pet-friendly",
      "in-unit laundry",
      "gym access",
      "dishwasher",
      "storage unit",
      "rooftop access",
    ],
    type: "condo",
    availableFrom: "2025-09-07",
    description:
      "Discover 3 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, in-unit laundry, gym access, dishwasher, storage unit, and rooftop access. Available starting September 7, 2025 for $4250/month. Don't miss out!",
  },
  {
    id: 155,
    title: "Charming 2 Bed Apartment in Atlanta",
    location: "Atlanta, GA",
    price: 2350,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["central AC", "dishwasher", "gym access", "rooftop access"],
    type: "apartment",
    availableFrom: "2025-11-26",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, dishwasher, gym access, and rooftop access. Available starting November 26, 2025 for $2350/month. Don't miss out!",
  },
  {
    id: 156,
    title: "Modern 4 Bed Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 2800,
    bedrooms: 4,
    bathrooms: 2,
    amenities: ["pet-friendly", "parking"],
    type: "apartment",
    availableFrom: "2025-12-21",
    description:
      "Discover 4 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly and parking. Available starting December 21, 2025 for $2800/month. Don't miss out!",
  },
  {
    id: 157,
    title: "Modern 3 Bed House in Boston",
    location: "Boston, MA",
    price: 7050,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["balcony", "doorman", "gym access", "furnished"],
    type: "house",
    availableFrom: "2025-09-02",
    description:
      "Discover 3 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like balcony, doorman, gym access, and furnished. Available starting September 2, 2025 for $7050/month. Don't miss out!",
  },
  {
    id: 158,
    title: "Spacious 1 Bed Condo in Brooklyn",
    location: "Brooklyn, NY",
    price: 3850,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["furnished", "pool access", "doorman", "wifi"],
    type: "condo",
    availableFrom: "2025-12-04",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, pool access, doorman, and wifi. Available starting December 4, 2025 for $3850/month. Don't miss out!",
  },
  {
    id: 159,
    title: "Luxurious 1 Bed Apartment in Queens",
    location: "Queens, NY",
    price: 2150,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "in-unit laundry", "hardwood floors"],
    type: "apartment",
    availableFrom: "2025-08-08",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, in-unit laundry, and hardwood floors. Available starting August 8, 2025 for $2150/month. Don't miss out!",
  },
  {
    id: 160,
    title: "Modern 1 Bed Condo in Nashville",
    location: "Nashville, TN",
    price: 2000,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "hardwood floors", "in-unit laundry"],
    type: "condo",
    availableFrom: "2025-10-06",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, hardwood floors, and in-unit laundry. Available starting October 6, 2025 for $2000/month. Don't miss out!",
  },
  {
    id: 161,
    title: "Modern 1 Bed Condo in San Francisco",
    location: "San Francisco, CA",
    price: 4050,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "storage unit", "furnished", "balcony", "wifi"],
    type: "condo",
    availableFrom: "2025-09-15",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, storage unit, furnished, balcony, and wifi. Available starting September 15, 2025 for $4050/month. Don't miss out!",
  },
  {
    id: 162,
    title: "Quaint 5 Bed Apartment in Denver",
    location: "Denver, CO",
    price: 4650,
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["hardwood floors", "balcony", "furnished"],
    type: "apartment",
    availableFrom: "2025-11-23",
    description:
      "Discover 5 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, balcony, and furnished. Available starting November 23, 2025 for $4650/month. Don't miss out!",
  },
  {
    id: 163,
    title: "Luxurious 4 Bed House in Manhattan",
    location: "Manhattan, NY",
    price: 9950,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["pet-friendly", "gym access", "hardwood floors", "pool access"],
    type: "house",
    availableFrom: "2025-09-02",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, gym access, hardwood floors, and pool access. Available starting September 2, 2025 for $9950/month. Don't miss out!",
  },
  {
    id: 164,
    title: "Cozy 3 Bed Apartment in Portland",
    location: "Portland, OR",
    price: 3100,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["pet-friendly", "shared garden", "rooftop access"],
    type: "apartment",
    availableFrom: "2025-09-28",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pet-friendly, shared garden, and rooftop access. Available starting September 28, 2025 for $3100/month. Don't miss out!",
  },
  {
    id: 165,
    title: "Modern 5 Bed House in Miami",
    location: "Miami, FL",
    price: 6300,
    bedrooms: 5,
    bathrooms: 3,
    amenities: [
      "in-unit laundry",
      "furnished",
      "dishwasher",
      "parking",
      "central AC",
    ],
    type: "house",
    availableFrom: "2025-07-28",
    description:
      "Discover 5 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like in-unit laundry, furnished, dishwasher, parking, and central AC. Available starting July 28, 2025 for $6300/month. Don't miss out!",
  },
  {
    id: 166,
    title: "Spacious 1 Bed Condo in Chicago",
    location: "Chicago, IL",
    price: 2700,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "wifi",
      "hardwood floors",
      "gym access",
      "dishwasher",
      "doorman",
    ],
    type: "condo",
    availableFrom: "2025-07-16",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like wifi, hardwood floors, gym access, dishwasher, and doorman. Available starting July 16, 2025 for $2700/month. Don't miss out!",
  },
  {
    id: 167,
    title: "Charming Studio Apartment in Los Angeles",
    location: "Los Angeles, CA",
    price: 2550,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["furnished", "pool access", "balcony", "doorman"],
    type: "studio",
    availableFrom: "2025-11-20",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, pool access, balcony, and doorman. Available starting November 20, 2025 for $2550/month. Don't miss out!",
  },
  {
    id: 168,
    title: "Cozy Studio Apartment in Seattle",
    location: "Seattle, WA",
    price: 3200,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["furnished", "dishwasher", "balcony", "wifi", "gym access"],
    type: "studio",
    availableFrom: "2025-12-28",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, dishwasher, balcony, wifi, and gym access. Available starting December 28, 2025 for $3200/month. Don't miss out!",
  },
  {
    id: 169,
    title: "Spacious Studio Apartment in Atlanta",
    location: "Atlanta, GA",
    price: 1700,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["parking", "pet-friendly", "hardwood floors"],
    type: "studio",
    availableFrom: "2025-07-13",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking, pet-friendly, and hardwood floors. Available starting July 13, 2025 for $1700/month. Don't miss out!",
  },
  {
    id: 170,
    title: "Bright 3 Bed Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 2600,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["dishwasher", "balcony", "gym access", "parking", "wifi"],
    type: "apartment",
    availableFrom: "2025-09-02",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, balcony, gym access, parking, and wifi. Available starting September 2, 2025 for $2600/month. Don't miss out!",
  },
  {
    id: 171,
    title: "Cozy 1 Bed Townhouse in Boston",
    location: "Boston, MA",
    price: 4050,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "rooftop access",
      "in-unit laundry",
      "dishwasher",
      "pool access",
    ],
    type: "townhouse",
    availableFrom: "2025-12-25",
    description:
      "Discover 1 spacious bedroom in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, rooftop access, in-unit laundry, dishwasher, and pool access. Available starting December 25, 2025 for $4050/month. Don't miss out!",
  },
  {
    id: 172,
    title: "Charming 3 Bed Townhouse in Brooklyn",
    location: "Brooklyn, NY",
    price: 7250,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["furnished", "rooftop access", "balcony", "wifi"],
    type: "townhouse",
    availableFrom: "2026-01-13",
    description:
      "Discover 3 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, rooftop access, balcony, and wifi. Available starting January 13, 2026 for $7250/month. Don't miss out!",
  },
  {
    id: 173,
    title: "Modern 2 Bed Condo in Manhattan",
    location: "Manhattan, NY",
    price: 6300,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "hardwood floors",
      "pool access",
      "balcony",
      "in-unit laundry",
      "storage unit",
    ],
    type: "condo",
    availableFrom: "2025-10-14",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, pool access, balcony, in-unit laundry, and storage unit. Available starting October 14, 2025 for $6300/month. Don't miss out!",
  },
  {
    id: 174,
    title: "Luxurious 3 Bed Apartment in Queens",
    location: "Queens, NY",
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["rooftop access", "wifi", "doorman", "balcony"],
    type: "apartment",
    availableFrom: "2025-10-15",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, wifi, doorman, and balcony. Available starting October 15, 2025 for $2800/month. Don't miss out!",
  },
  {
    id: 175,
    title: "Bright 4 Bed House in Los Angeles",
    location: "Los Angeles, CA",
    price: 6050,
    bedrooms: 4,
    bathrooms: 3,
    amenities: [
      "dishwasher",
      "central AC",
      "in-unit laundry",
      "furnished",
      "storage unit",
      "pool access",
    ],
    type: "house",
    availableFrom: "2025-09-09",
    description:
      "Discover 4 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like dishwasher, central AC, in-unit laundry, furnished, storage unit, and pool access. Available starting September 9, 2025 for $6050/month. Don't miss out!",
  },
  {
    id: 176,
    title: "Charming 2 Bed Apartment in Austin",
    location: "Austin, TX",
    price: 3150,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["hardwood floors", "wifi", "dishwasher"],
    type: "apartment",
    availableFrom: "2025-12-14",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, wifi, and dishwasher. Available starting December 14, 2025 for $3150/month. Don't miss out!",
  },
  {
    id: 177,
    title: "Bright 3 Bed Apartment in Miami",
    location: "Miami, FL",
    price: 4200,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "furnished",
      "hardwood floors",
      "dishwasher",
      "parking",
      "balcony",
    ],
    type: "apartment",
    availableFrom: "2025-10-04",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, hardwood floors, dishwasher, parking, and balcony. Available starting October 4, 2025 for $4200/month. Don't miss out!",
  },
  {
    id: 178,
    title: "Charming 1 Bed Condo in Seattle",
    location: "Seattle, WA",
    price: 3200,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["gym access", "doorman", "hardwood floors", "central AC"],
    type: "condo",
    availableFrom: "2025-07-29",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, doorman, hardwood floors, and central AC. Available starting July 29, 2025 for $3200/month. Don't miss out!",
  },
  {
    id: 179,
    title: "Cozy 3 Bed Townhouse in Denver",
    location: "Denver, CO",
    price: 4000,
    bedrooms: 3,
    bathrooms: 2,
    amenities:
      ["hardwood floors", "wifi", "balcony", "pool access", "in-unit laundry"],
    type: "townhouse",
    availableFrom: "2025-08-01",
    description:
      "Discover 3 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, wifi, balcony, pool access, and in-unit laundry. Available starting August 1, 2025 for $4000/month. Don't miss out!",
  },
  {
    id: 180,
    title: "Modern 3 Bed Apartment in Atlanta",
    location: "Atlanta, GA",
    price: 2850,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "central AC",
      "shared garden",
      "furnished",
      "pool access",
      "rooftop access",
      "dishwasher",
    ],
    type: "apartment",
    availableFrom: "2025-10-27",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, shared garden, furnished, pool access, rooftop access, and dishwasher. Available starting October 27, 2025 for $2850/month. Don't miss out!",
  },
  {
    id: 181,
    title: "Charming 5 Bed Apartment in Nashville",
    location: "Nashville, TN",
    price: 4200,
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["central AC", "balcony", "parking"],
    type: "apartment",
    availableFrom: "2025-10-09",
    description:
      "Discover 5 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, balcony, and parking. Available starting October 9, 2025 for $4200/month. Don't miss out!",
  },
  {
    id: 182,
    title: "Quaint Studio Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 1850,
    bedrooms: 0,
    bathrooms: 1,
    amenities: ["gym access", "balcony", "hardwood floors"],
    type: "studio",
    availableFrom: "2025-10-18",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, balcony, and hardwood floors. Available starting October 18, 2025 for $1850/month. Don't miss out!",
  },
  {
    id: 183,
    title: "Spacious 2 Bed Apartment in Boston",
    location: "Boston, MA",
    price: 4500,
    bedrooms: 2,
    bathrooms: 2,
    amenities: [
      "rooftop access",
      "storage unit",
      "in-unit laundry",
      "gym access",
    ],
    type: "apartment",
    availableFrom: "2025-12-14",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, storage unit, in-unit laundry, and gym access. Available starting December 14, 2025 for $4500/month. Don't miss out!",
  },
  {
    id: 184,
    title: "Modern Studio Apartment in Brooklyn",
    location: "Brooklyn, NY",
    price: 3150,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "dishwasher",
      "pool access",
      "doorman",
      "in-unit laundry",
    ],
    type: "studio",
    availableFrom: "2026-01-20",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, dishwasher, pool access, doorman, and in-unit laundry. Available starting January 20, 2026 for $3150/month. Don't miss out!",
  },
  {
    id: 185,
    title: "Charming 2 Bed Townhouse in Manhattan",
    location: "Manhattan, NY",
    price: 6300,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["gym access", "doorman", "dishwasher", "wifi"],
    type: "townhouse",
    availableFrom: "2025-08-25",
    description:
      "Discover 2 spacious bedrooms in this lovely townhouse. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, doorman, dishwasher, and wifi. Available starting August 25, 2025 for $6300/month. Don't miss out!",
  },
  {
    id: 186,
    title: "Modern 1 Bed Condo in San Francisco",
    location: "San Francisco, CA",
    price: 5000,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["gym access", "balcony", "in-unit laundry", "pool access"],
    type: "condo",
    availableFrom: "2025-11-27",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, balcony, in-unit laundry, and pool access. Available starting November 27, 2025 for $5000/month. Don't miss out!",
  },
  {
    id: 187,
    title: "Cozy 2 Bed Condo in Los Angeles",
    location: "Los Angeles, CA",
    price: 4050,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      "hardwood floors",
      "doorman",
      "furnished",
      "central AC",
      "in-unit laundry",
    ],
    type: "condo",
    availableFrom: "2025-10-09",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, doorman, furnished, central AC, and in-unit laundry. Available starting October 9, 2025 for $4050/month. Don't miss out!",
  },
  {
    id: 188,
    title: "Spacious 5 Bed House in Chicago",
    location: "Chicago, IL",
    price: 6450,
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["pool access", "parking", "dishwasher", "shared garden"],
    type: "house",
    availableFrom: "2025-08-27",
    description:
      "Discover 5 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pool access, parking, dishwasher, and shared garden. Available starting August 27, 2025 for $6450/month. Don't miss out!",
  },
  {
    id: 189,
    title: "Luxurious 2 Bed Apartment in Austin",
    location: "Austin, TX",
    price: 3050,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      "furnished",
      "rooftop access",
      "central AC",
      "in-unit laundry",
      "balcony",
      "wifi",
    ],
    type: "apartment",
    availableFrom: "2025-08-24",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like furnished, rooftop access, central AC, in-unit laundry, balcony, and wifi. Available starting August 24, 2025 for $3050/month. Don't miss out!",
  },
  {
    id: 190,
    title: "Spacious 1 Bed Apartment in Miami",
    location: "Miami, FL",
    price: 2400,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["balcony", "furnished", "central AC", "storage unit"],
    type: "apartment",
    availableFrom: "2025-08-07",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like balcony, furnished, central AC, and storage unit. Available starting August 7, 2025 for $2400/month. Don't miss out!",
  },
  {
    id: 191,
    title: "Modern Studio Apartment in Seattle",
    location: "Seattle, WA",
    price: 3100,
    bedrooms: 0,
    bathrooms: 1,
    amenities: [
      "doorman",
      "gym access",
      "pool access",
      "wifi",
      "central AC",
      "storage unit",
    ],
    type: "studio",
    availableFrom: "2026-01-09",
    description:
      "Discover a charming studio in this lovely studio. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like doorman, gym access, pool access, wifi, central AC, and storage unit. Available starting January 9, 2026 for $3100/month. Don't miss out!",
  },
  {
    id: 192,
    title: "Spacious 3 Bed Apartment in Denver",
    location: "Denver, CO",
    price: 3500,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      "hardwood floors",
      "storage unit",
      "pool access",
      "pet-friendly",
      "parking",
    ],
    type: "apartment",
    availableFrom: "2025-07-21",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like hardwood floors, storage unit, pool access, pet-friendly, and parking. Available starting July 21, 2025 for $3500/month. Don't miss out!",
  },
  {
    id: 193,
    title: "Charming 1 Bed Apartment in Atlanta",
    location: "Atlanta, GA",
    price: 1400,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["central AC", "in-unit laundry", "wifi"],
    type: "apartment",
    availableFrom: "2025-08-23",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like central AC, in-unit laundry, and wifi. Available starting August 23, 2025 for $1400/month. Don't miss out!",
  },
  {
    id: 194,
    title: "Cozy 3 Bed Apartment in Nashville",
    location: "Nashville, TN",
    price: 2700,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["pool access", "dishwasher", "gym access"],
    type: "apartment",
    availableFrom: "2025-10-25",
    description:
      "Discover 3 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like pool access, dishwasher, and gym access. Available starting October 25, 2025 for $2700/month. Don't miss out!",
  },
  {
    id: 195,
    title: "Luxurious 2 Bed Apartment in Philadelphia",
    location: "Philadelphia, PA",
    price: 2350,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      "parking",
      "central AC",
      "dishwasher",
      "wifi",
      "in-unit laundry",
      "balcony",
    ],
    type: "apartment",
    availableFrom: "2025-08-16",
    description:
      "Discover 2 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like parking, central AC, dishwasher, wifi, in-unit laundry, and balcony. Available starting August 16, 2025 for $2350/month. Don't miss out!",
  },
  {
    id: 196,
    title: "Modern 2 Bed Condo in Boston",
    location: "Boston, MA",
    price: 5450,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["rooftop access", "dishwasher", "central AC", "gym access"],
    type: "condo",
    availableFrom: "2025-11-24",
    description:
      "Discover 2 spacious bedrooms in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, dishwasher, central AC, and gym access. Available starting November 24, 2025 for $5450/month. Don't miss out!",
  },
  {
    id: 197,
    title: "Luxurious 1 Bed Condo in Brooklyn",
    location: "Brooklyn, NY",
    price: 4000,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      "gym access",
      "balcony",
      "doorman",
      "hardwood floors",
      "central AC",
    ],
    type: "condo",
    availableFrom: "2025-10-07",
    description:
      "Discover 1 spacious bedroom in this lovely condo. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like gym access, balcony, doorman, hardwood floors, and central AC. Available starting October 7, 2025 for $4000/month. Don't miss out!",
  },
  {
    id: 198,
    title: "Spacious 4 Bed Apartment in Queens",
    location: "Queens, NY",
    price: 4150,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["shared garden", "wifi", "pool access"],
    type: "apartment",
    availableFrom: "2025-12-24",
    description:
      "Discover 4 spacious bedrooms in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like shared garden, wifi, and pool access. Available starting December 24, 2025 for $4150/month. Don't miss out!",
  },
  {
    id: 199,
    title: "Bright 5 Bed House in Manhattan",
    location: "Manhattan, NY",
    price: 9950,
    bedrooms: 5,
    bathrooms: 3,
    amenities: [
      "balcony",
      "parking",
      "pool access",
      "storage unit",
      "rooftop access",
    ],
    type: "house",
    availableFrom: "2025-09-02",
    description:
      "Discover 5 spacious bedrooms in this lovely house. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like balcony, parking, pool access, storage unit, and rooftop access. Available starting September 2, 2025 for $9950/month. Don't miss out!",
  },
  {
    id: 200,
    title: "Modern 1 Bed Apartment in San Francisco",
    location: "San Francisco, CA",
    price: 4200,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["rooftop access", "gym access", "balcony", "doorman", "wifi"],
    type: "apartment",
    availableFrom: "2025-11-09",
    description:
      "Discover 1 spacious bedroom in this fantastic apartment. Located in a vibrant neighborhood, this home offers comfort and convenience. Enjoy features like rooftop access, gym access, balcony, doorman, and wifi. Available starting November 9, 2025 for $4200/month. Don't miss out!",
  },
];
